train:
    shuffle: on
    num_worker: 4
    batch_size: 8
    epoch: 100
    device: cuda
    output_dir: ATClsResnet
    session_dir: balanceOnDataPreTrainOn100ePochALLData
    balance: on
    save_step: 2000
    pre_train: on
    netname: ATresnet
    resume: off
    resume_path: None

test:
    device: gpu
    dir_name: test_out




