data:
  dataRoot: 'nii'
  fileNameTemplate: 'pic{}.nii.gz'
  fileTSeedTemplate: 'pic{}TSeed.nii.gz'
  fileCrackTemplate: 'pic{}Crack.nii.gz'
  fileSeedTemplate: 'pic{}Seed.nii.gz'

  splitedOnEntity: On
  splitedImagesRate: 0.2 # usage percentage 
  splitedRandomSeed: 10
  splitedImagesRange: [1, 38]

  totalRange: [1, 38] # always use interval
  tseedRange: [1, 19] # always use interval

  rangeMode: interval
  # default train and test range using patients
  trainRange: [1, 34]
  testRange: [34,38]

  levelset:
    rangeMode: interval
    range: [1, 19]

image:
  height: 512
  width: 512
  normal: 8
  gaussFilter: False
  gKernelSize: 5
  medianFilter: False
  medKernelSize: 5

