data:
  dataRoot: 'nii'
  fileNameTemplate: 'pic{}.nii.gz'
  fileTSeedTemplate: 'pic{}TSeed.nii.gz'
  fileCrackTemplate: 'pic{}Crack.nii.gz'
  fileSeedTemplate: 'pic{}Seed.nii.gz'
  tseedRange: [1, 19]
  trainRange: [1, 34]
  testRange: [34,38]
  levelset:
    range: [1, 19]

image:
  height: 512
  width: 512
  normal: 8
  gaussFilter: False
  gKernelSize: 5
  medianFilter: False
  medKernelSize: 5

