train:
    shuffle: on
    num_worker: 4
    batch_size: 8
    epoch: 50
    device: cuda
    output_dir: output
    netname: resnet50
    session_dir: auto

    balance: on
    save_step: 2000
    info_step: 100
    test_step: 600
    pre_train: on

    resume: off
    resume_path: None
    
data:
    splitedOnEntity: off # split on images or patients
    splitedImagesRate: 0.2 # if split on patients, the rates of split

    rangeMode: interval
    trainRange: [1, 34]
    testRange: [34,38]

loss:
    type: CE  # support CE or FOCAL
    gamma: 5 # FOCAL Gamma
    posWeight: 0.9 

optim:
    type: SGD
    momentum: 0.9  
    lr: 0.0001 # 1e-4 
    weight_decay: 0.01 #1e-2 

test:
    device: gpu
    dir_name: test_out




